spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

  application:
    name: pda-midterm-project

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
  profiles:
    include:
      - jwt
      - coolSMS
      - openai
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
fastapi:
  base-url: http://localhost:8000

server:
  port: 8080

data-server:
  url: http://localhost:8000

openai:
  api-key: ${OPENAI_API_KEY}
